=== weslleypg/programa-em-phyton-tcc-usp/9xx1_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://www.bcb.gov.br/cdsfn_schema.json",
  "type": "object",
  "title": "Esquema para validação das remessas da Central de Demonstrações Financeiras do Sistema Financeiro Nacional",
  "description": "Validação das remessas da CDSFN em formato JSON",
  "additionalProperties": false,
  "definitions": {
    "identificador" : {
      "$id": "#/raiz/definitions/identificador",
      "type": "string",
      "pattern": "^[a-zA-Z0-9._-]+$"
    },
    "stringvazia" : {
      "$id": "#/raiz/definitions/stringvazia",
      "type": "string",
      "pattern": "^$"
    },
    "valoresTemporais": {
      "$id": "#/raiz/definitions/valoresTemporais", 
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items":{
        "$id": "#/raiz/definitions/valoresTemporais/items", 
        "title": "Items", 
        "type": "object",
        "required": ["@dtBase", "@valor"],
        "properties": {
          "@dtBase": {"$ref": "#/definitions/identificador"},
          "@valor": {
            "$id": "#/raiz/definitions/valoresTemporais/items/valor", 
            "title": "Valor", 
            "type": "number"
          }
        }
      }
    },
    "contas": {
      "$id": "#/raiz/definitions/contas",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "title": "Contas",
      "additionalItems": false,
      "items": {
        "$id": "#/raiz/definitions/contas/items",
        "type": "object",
        "title": "Itens de conta",
        "additionalProperties": false,
        "required": ["@id", "@nivel", "@descricao", "@contaPai"],
        "properties": {
          "@id": {"$ref": "#/definitions/identificador"},
          "@nivel": {
            "$id": "#/raiz/definitions/contas/items/nivel",
            "type": "string",
            "pattern": "^[0-9]+([.][0-9]+)*$",
            "title": "Nível da conta"
          },
          "@descricao": {
            "$id": "#/raiz/definitions/contas/items/descricao",
            "type": "string",
            "title": "Descrição da conta"
          },
          "@contaPai": {
            "$id": "#/raiz/definitions/contas/items/contaPai",
            "oneOf": [
              {"$ref": "#/definitions/identificador"},
              {"type": "null"},
              {"$ref": "#/definitions/stringvazia"}
            ],
            "title": "Conta-pai na hierarquia de contas"
          },              
          "valoresIndividualizados": {"$ref": "#/definitions/valoresTemporais"},
          "valoresConsolidados": {"$ref": "#/definitions/valoresTemporais"}
        }
      }
    }

  },
  "oneOf": [
		{
			"required": ["@cnpj", "@codigoDocumento", "@tipoRemessa", "@dataBase", "@unidadeMedida", "datasBaseReferencia", "BalancoPatrimonial", "DemonstracaoDoResultado", "DemonstracaoDoResultadoAbrangente", "DemonstracaoDosFluxosDeCaixa", "DemonstracaoDasMutacoesDoPatrimonioLiquido"]
		},
		{
			"required": ["@cnpj", "@codigoDocumento", "@tipoRemessa", "@dataBase", "@unidadeMedida", "datasBaseReferencia", "BalancoPatrimonial", "DemonstracaoDeSobrasOuPerdas", "DemonstracaoDoResultadoAbrangente", "DemonstracaoDosFluxosDeCaixa", "DemonstracaoDasMutacoesDoPatrimonioLiquido"]
		}
	],  
  "properties": {
    "@cnpj": {
      "$id": "#/raiz/cnpj",
      "type": "string",
      "pattern": "^[0-9]{8}$",
      "title": "CNPJ",
	    "minLength": 8,
	    "maxLength": 8
    },
    "@codigoDocumento": {
      "$id": "#/raiz/codigoDocumento",
      "type": "string",
      "title": "Código do documento",
	    "enum": ["9011", "9311", "9031", "9331", "9061"]
    },
    "@tipoRemessa": {
      "$id": "#/raiz/tipoRemessa",
      "type": "string",
      "enum": ["I", "S"],
      "title": "Tipo de remessa",
      "description": "I=Inclusão, S=Substituição"
    },
    "@dataBase": {
      "$id": "#/raiz/dataBase",
      "type": "string",
      "pattern": "^(0[1-9]|1[0-2])[0-9]{4}$",
      "minLength": 6,
      "maxLength": 6,
      "title": "Data-base do documento",
      "description": "Formato MMAAAA"
    },
	  "@unidadeMedida": {
      "$id": "#/raiz/unidadeMedida",
      "type": "integer",
      "title": "Unidade de medida dos valores monetários informados no documento",
      "description": "Indica o multiplicador adotado para os valores em reais"
    },
    "datasBaseReferencia": {
      "$id": "#/raiz/datasBaseReferencia",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "title": "Datas-base referência informadas no documento",
      "description": "Conjunto de ids e datas-base",
      "additionalItems": false,
      "items": {
        "$id": "#/raiz/datasBaseReferencia/items",
        "type": "object",
        "title": "Itens de data-base referência",
        "additionalProperties": false,
        "required": ["@id","@data"],
        "properties": {
          "@id": {"$ref": "#/definitions/identificador"},
          "@data": {
            "$id": "#/raiz/datasBaseReferencia/items/data",
            "type": "string",
            "pattern": "^(A|S|T|I)(0[1-9]|1[0-2])[0-9]{4}$",
            "minLength": 7,
            "maxLength": 7,
            "title": "Data-base",
            "description": "Formato PMMAAAA, onde P refere-se ao período de apuração (A=ano, S=semestre, T=trimestre, I=Saldo acumulado nas declarações intermediarias), MM=mês e AAAA=ano"
          }
        }
      }
    },
    "BalancoPatrimonial": {
      "$id": "#/raiz/balancoPatrimonial",
      "type": "object",
      "title": "Balanço patrimonial",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "BalancoPatrimonialConsolidado": {
      "$id": "#/raiz/balancoPatrimonialConsolidado",
      "type": "object",
      "title": "Balanço patrimonial consolidado",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDoResultado": {
      "$id": "#/raiz/demonstracaoDoResultado",
      "type": "object",
      "title": "Demonstração do resultado",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDoResultadoConsolidada": {
      "$id": "#/raiz/demonstracaoDoResultadoConsolidada",
      "type": "object",
      "title": "Demonstração do resultado consolidada",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
	"DemonstracaoDeSobrasOuPerdas": {
      "$id": "#/raiz/DemonstracaoDeSobrasOuPerdas",
      "type": "object",
      "title": "Demonstração de sobras ou perdas",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
	"DemonstracaoDeSobrasOuPerdasConsolidada": {
      "$id": "#/raiz/DemonstracaoDeSobrasOuPerdasConsolidada",
      "type": "object",
      "title": "Demonstração de sobras ou perdas consolidada",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDoResultadoAbrangente": {
      "$id": "#/raiz/demonstracaoDoResultadoAbrangente",
      "type": "object",
      "title": "Demonstração do resultado abrangente",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDoResultadoAbrangenteConsolidada": {
      "$id": "#/raiz/demonstracaoDoResultadoAbrangenteConsolidada",
      "type": "object",
      "title": "Demonstração do resultado abrangente consolidada",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDosFluxosDeCaixa": {
      "$id": "#/raiz/demonstracaoDosFluxosDeCaixa",
      "type": "object",
      "title": "Demonstração dos fluxos de caixa",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDosFluxosDeCaixaConsolidada": {
      "$id": "#/raiz/demonstracaoDosFluxosDeCaixaConsolidada",
      "type": "object",
      "title": "Demonstração dos fluxos de caixa consolidada",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDasMutacoesDoPatrimonioLiquido": {
      "$id": "#/raiz/demonstracaoDasMutacoesDoPatrimonioLiquido",
      "type": "object",
      "title": "Demonstração das mutações do patrimônio líquido",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDasMutacoesDoPatrimonioLiquidoConsolidada": {
      "$id": "#/raiz/demonstracaoDasMutacoesDoPatrimonioLiquidoConsolidada",
      "type": "object",
      "title": "Demonstração das mutações do patrimônio líquido consolidada",
      "additionalProperties": false,
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDosRecursosDeConsorcioConsolidada": {
      "$id": "#/raiz/demonstracaoDosRecursosDeConsorcioConsolidada",
      "type": "object",
      "title": "Demonstração dos recursos de consórcio consolidada",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    },
    "DemonstracaoDeVariacoesNasDisponibilidadesDeGruposConsolidada": {
      "$id": "#/raiz/demonstracaoDeVariacoesNasDisponibilidadesDeGruposConsolidada",
      "type": "object",
      "title": "Demonstração de variações nas disponibilidades de grupos consolidada",
      "additionalProperties": false,
      "required": ["contas"],
      "properties": {
        "contas": {"$ref": "#/definitions/contas"}
      }
    }
  }
}

=== weslleypg/programa-em-phyton-tcc-usp/data/raw/202412-9011-10573521.json
{"@cnpj":"10573521","@codigoDocumento":"9011","@tipoRemessa":"I","@unidadeMedida":1000,"@dataBase":"122024","datasBaseReferencia":[{"@id":"dt7","@data":"S062024"},{"@id":"dt1","@data":"A122024"},{"@id":"dt5","@data":"A122022"},{"@id":"dt2","@data":"A122023"}],"BalancoPatrimonial":{"contas":[{"@id":"1","@nivel":"1","@descricao":"ATIVO","@contaPai":"","valoresIndividualizados":[{"@dtBase":"dt1","@valor":60153400},{"@dtBase":"dt2","@valor":33522846}]},{"@id":"2","@nivel":"1.1","@descricao":"Disponibilidades","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":716323},{"@dtBase":"dt2","@valor":582301}]},{"@id":"3","@nivel":"1.2","@descricao":"Instrumentos financeiros","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":57807176},{"@dtBase":"dt2","@valor":31593739}]},{"@id":"4","@nivel":"1.2.1","@descricao":"Títulos e valores mobiliários","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":26027482},{"@dtBase":"dt2","@valor":12538862}]},{"@id":"5","@nivel":"1.2.2","@descricao":"Instrumentos financeiros derivativos ativos","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":34576},{"@dtBase":"dt2","@valor":89}]},{"@id":"6","@nivel":"1.2.3","@descricao":"Outros ativos a receber","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":31745118},{"@dtBase":"dt2","@valor":19054788}]},{"@id":"7","@nivel":"1.3","@descricao":"Impostos e contribuições a compensar","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":970275},{"@dtBase":"dt2","@valor":614567}]},{"@id":"8","@nivel":"1.4","@descricao":"Provisão p/ créditos de liquidações duvidosas","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-532150},{"@dtBase":"dt2","@valor":-249070}]},{"@id":"9","@nivel":"1.5","@descricao":"Ativos fiscais diferidos","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":694420},{"@dtBase":"dt2","@valor":484565}]},{"@id":"10","@nivel":"1.6","@descricao":"Imobilizado de uso","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":77384},{"@dtBase":"dt2","@valor":75194}]},{"@id":"11","@nivel":"1.7","@descricao":"Depreciações","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-42479},{"@dtBase":"dt2","@valor":-36284}]},{"@id":"12","@nivel":"1.8","@descricao":"Intangível","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":810840},{"@dtBase":"dt2","@valor":1112795}]},{"@id":"13","@nivel":"1.9","@descricao":"Amortizações","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-348389},{"@dtBase":"dt2","@valor":-654961}]},{"@id":"14","@nivel":"2","@descricao":"PASSIVO","@contaPai":"","valoresIndividualizados":[{"@dtBase":"dt1","@valor":56913841},{"@dtBase":"dt2","@valor":31676567}]},{"@id":"15","@nivel":"2.1","@descricao":"Depósitos e demais instrumentos financeiros","@contaPai":"14","valoresIndividualizados":[{"@dtBase":"dt1","@valor":54675183},{"@dtBase":"dt2","@valor":29920702}]},{"@id":"16","@nivel":"2.1.1","@descricao":"Depósitos","@contaPai":"15","valoresIndividualizados":[{"@dtBase":"dt1","@valor":28518869},{"@dtBase":"dt2","@valor":14774829}]},{"@id":"17","@nivel":"2.1.2","@descricao":"Relações interfinanceiras","@contaPai":"15","valoresIndividualizados":[{"@dtBase":"dt1","@valor":10391748},{"@dtBase":"dt2","@valor":4364574}]},{"@id":"18","@nivel":"2.1.3","@descricao":"Obrigações por empréstimos","@contaPai":"15","valoresIndividualizados":[{"@dtBase":"dt1","@valor":5936},{"@dtBase":"dt2","@valor":205}]},{"@id":"19","@nivel":"2.1.4","@descricao":"Instrumentos financeiros derivativos passivos","@contaPai":"15","valoresIndividualizados":[{"@dtBase":"dt2","@valor":16817}]},{"@id":"20","@nivel":"2.1.5","@descricao":"Outros passivos diversos","@contaPai":"15","valoresIndividualizados":[{"@dtBase":"dt1","@valor":15758630},{"@dtBase":"dt2","@valor":10764277}]},{"@id":"21","@nivel":"2.2","@descricao":"Outras obrigações","@contaPai":"14","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1066565},{"@dtBase":"dt2","@valor":837939}]},{"@id":"22","@nivel":"2.3","@descricao":"Provisões","@contaPai":"14","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1161117},{"@dtBase":"dt2","@valor":917926}]},{"@id":"23","@nivel":"2.4","@descricao":"Obrigações fiscais diferidas","@contaPai":"14","valoresIndividualizados":[{"@dtBase":"dt1","@valor":10976}]},{"@id":"24","@nivel":"3","@descricao":"PATRIMÔNIO LÍQUIDO","@contaPai":"","valoresIndividualizados":[{"@dtBase":"dt1","@valor":3239559},{"@dtBase":"dt2","@valor":1846279}]},{"@id":"25","@nivel":"3.1","@descricao":"Capital social","@contaPai":"24","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1247340},{"@dtBase":"dt2","@valor":982340}]},{"@id":"26","@nivel":"3.1.1","@descricao":"Capital social integralizado","@contaPai":"25","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1247340},{"@dtBase":"dt2","@valor":1237340}]},{"@id":"27","@nivel":"3.1.2","@descricao":"Aumento de capital - em aprovação","@contaPai":"25","valoresIndividualizados":[{"@dtBase":"dt2","@valor":10000}]},{"@id":"28","@nivel":"3.1.3","@descricao":"Capital social a realizar","@contaPai":"25","valoresIndividualizados":[{"@dtBase":"dt2","@valor":-265000}]},{"@id":"29","@nivel":"3.2","@descricao":"Outros resultados abrangentes","@contaPai":"24","valoresIndividualizados":[{"@dtBase":"dt1","@valor":21308},{"@dtBase":"dt2","@valor":-12483}]},{"@id":"30","@nivel":"3.3","@descricao":"Reserva de Lucros","@contaPai":"24","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1970911},{"@dtBase":"dt2","@valor":876422}]}]},"DemonstracaoDoResultado":{"contas":[{"@id":"1","@nivel":"1.1.1","@descricao":"RECEITAS DE INTERMEDIAÇÃO FINANCEIRA ","@contaPai":"7","valoresIndividualizados":[{"@dtBase":"dt1","@valor":814063},{"@dtBase":"dt2","@valor":787974}]},{"@id":"2","@nivel":"1.1.1.1","@descricao":"Resultado de operações com títulos e valores mobiliários","@contaPai":"1","valoresIndividualizados":[{"@dtBase":"dt1","@valor":814063},{"@dtBase":"dt2","@valor":787974}]},{"@id":"3","@nivel":"1.1.2","@descricao":"DESPESAS DE INTERMEDIAÇÃO FINANCEIRA ","@contaPai":"7","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-102469},{"@dtBase":"dt2","@valor":-7832}]},{"@id":"4","@nivel":"1.1.2.1","@descricao":"Resultado com instrumentos financeiros derivativos","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":24322},{"@dtBase":"dt2","@valor":-73359}]},{"@id":"5","@nivel":"1.1.2.2","@descricao":"Obrigações por empréstimos","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-2569},{"@dtBase":"dt2","@valor":24043}]},{"@id":"6","@nivel":"1.1.2.3","@descricao":"Resultado de variação cambial","@contaPai":"3","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-124222},{"@dtBase":"dt2","@valor":41484}]},{"@id":"7","@nivel":"1.1","@descricao":"RESULTADO BRUTO DA INTERMEDIAÇÃO FINANCEIRA","@contaPai":"17","valoresIndividualizados":[{"@dtBase":"dt1","@valor":711594},{"@dtBase":"dt2","@valor":780142}]},{"@id":"8","@nivel":"1.2","@descricao":"OUTRAS RECEITAS/DESPESAS OPERACIONAIS","@contaPai":"17","valoresIndividualizados":[{"@dtBase":"dt1","@valor":923699},{"@dtBase":"dt2","@valor":-101397}]},{"@id":"9","@nivel":"1.2.1","@descricao":"Receitas de prestação de serviços e operacionais","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":16185125},{"@dtBase":"dt2","@valor":14832788}]},{"@id":"10","@nivel":"1.2.2","@descricao":"Renda de antecipação por obrigação de transação de pagamento","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1348308}]},{"@id":"11","@nivel":"1.2.3","@descricao":"Despesas de pessoal","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-707050},{"@dtBase":"dt2","@valor":-623317}]},{"@id":"12","@nivel":"1.2.4","@descricao":"Despesas administrativas","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-1604157},{"@dtBase":"dt2","@valor":-1127683}]},{"@id":"13","@nivel":"1.2.5","@descricao":"Despesas tributárias","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-2276484},{"@dtBase":"dt2","@valor":-1942338}]},{"@id":"14","@nivel":"1.2.6","@descricao":"Despesa direta por transações de pagamentos","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-3062653},{"@dtBase":"dt2","@valor":-2820793}]},{"@id":"15","@nivel":"1.2.7","@descricao":"Despesa com serviços ligados a transações de pagamento","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-5498690},{"@dtBase":"dt2","@valor":-3816041}]},{"@id":"16","@nivel":"1.2.8","@descricao":"Outras despesas operacionais","@contaPai":"8","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-3460700},{"@dtBase":"dt2","@valor":-4604013}]},{"@id":"17","@nivel":"1","@descricao":"RESULTADO OPERACIONAL","@contaPai":"","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1635293},{"@dtBase":"dt2","@valor":678745}]},{"@id":"18","@nivel":"2.1","@descricao":"RESULTADO ANTES DA TRIBUTAÇÃO SOBRE O LUCRO","@contaPai":"23","valoresIndividualizados":[{"@dtBase":"dt1","@valor":1635293},{"@dtBase":"dt2","@valor":678745}]},{"@id":"19","@nivel":"2.2","@descricao":"IMPOSTO DE RENDA E CONTRIBUIÇÃO SOCIAL","@contaPai":"23","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-448023},{"@dtBase":"dt2","@valor":-222628}]},{"@id":"20","@nivel":"2.2.1","@descricao":"Imposto de renda corrente","@contaPai":"19","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-480858},{"@dtBase":"dt2","@valor":-417958}]},{"@id":"21","@nivel":"2.2.2","@descricao":"Contribuição social corrente","@contaPai":"19","valoresIndividualizados":[{"@dtBase":"dt1","@valor":-183452},{"@dtBase":"dt2","@valor":-156560}]},{"@id":"22","@nivel":"2.2.3","@descricao":"Imposto de renda e contribuição social diferido","@contaPai":"19","valoresIndividualizados":[{"@dtBase":"dt1","@valor":216287},{"@dtBase":"dt2","@valor":351890}]},{"@id":"23","@nivel":"2","@descricao":"LUCRO LÍQUIDO DO EXERCÍCIO","@contaPai":"","valoresIndividu
